jenkins:
  authorizationStrategy:
    # roleBased:
    #   roles:
    #     global:
    #     - name: "Administrators"
    #       description: "Jenkins Administrators"
    #       permissions:
    #       - "Overall/Administer"
    #       assignments:
    #         - "admin"
    #     - name: "Read Only"
    #       description: "Read-only Users"
    #       permissions:
    #       - "Overall/Read"
    #       - "Job/Discover"
    #       assignments:
    #       - "anonymous"
    #     agents:
    #     - name: "Swarm Agents"
    #       description: "Agents added using the Swarm plugin"
    #       pattern: "build-*"
    #       permissions:
    #       - "Agent/Build"
    #       - "Agent/Configure"
    #       - "Agent/Connect"
    #       - "Agent/Create"
    #       - "Agent/Delete"
    #       - "Agent/Disconnect"
    #       assignments:
    #       - "agent"
    projectMatrix:
      grantedPermissions:
      - "Agent/Build:agent"
      - "Agent/Configure:agent"
      - "Agent/Connect:agent"
      - "Agent/Create:agent"
      - "Agent/Delete:agent"
      - "Agent/Disconnect:agent"
      - "Overall/Administer:admin"
      - "Job/Discover:anonymous"
      - "Overall/Read:anonymous"
  disableRememberMe: true
  labelString: "master"
  mode: EXCLUSIVE
  numExecutors: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "my-bitbucket-creds"
              username: "some-user"
              password: "some-password"
              description: "Username/Password Credentials for BitBucket"
unclassified:
  simple-theme-plugin:
    elements:
    - cssUrl:
        url: "/userContent/branding.css"
